# ######################################################################################################
# # CI/CD steps for Cloud Build to get a compiled TFX pipeline ready for exectuion.
# # Referenced from:
# # https://github.com/GoogleCloudPlatform/mlops-with-vertex-ai/blob/main/build/pipeline-deployment.yaml
# ######################################################################################################

# steps:
# # Clone the repository.
# - name: 'gcr.io/cloud-builders/git'
#   args: ['clone', '--single-branch', '--branch',
#          'main', 'https://github.com/deep-diver/Model-Training-as-a-CI-CD-System',
#          '--depth', '1',
#          '--verbose']
#   id: 'Clone Repository'
# logsBucket: 'gs://aivertex-bucket/custom_model_bucket/'


# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:sarath2812/gcp_vertexai
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# - name: python
# #   entrypoint: pip 
#   args: 
#   -     pip install -r requirements.txt
#   -     python ./pipeline/pipeline_kfp.py
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 
#            'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/peak-catbird-324206/gcp_vertexai/myimage:v1', '.']

# - name: python
#   entrypoint: pip 
#   args: ["install","-r","requirements.txt"]

# - name: python
#   entrypoint: python
#   args: ["./pipeline/pipeline_kfp.py"]
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh

# - name: python
#   entrypoint: python
#   args: ["./pipeline/pipeline_kfp.py"]
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh

# - name: 'python'
#     args: 
#     - -C
#     - |
#        cp . ./
#        python ./pipeline/pipeline_kfp.py
#    volumes:
#   - name: 'ssh'
#     path: /root/.ssh

# - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 
#            'us-central1-docker.pkg.dev/peak-catbird-324206/cicdimage:v1', '.']    

availableSecrets:
  secretManager:
  - versionName: projects/584418773784/secrets/git-secret-key/versions/1
    env: 'SSH_KEY'
logsBucket: 'gs://aivertex-bucket/custom_model_bucket/'