######################################################################################################
# CI/CD steps for Cloud Build to get a compiled TFX pipeline ready for exectuion.
# Referenced from:
# https://github.com/GoogleCloudPlatform/mlops-with-vertex-ai/blob/main/build/pipeline-deployment.yaml
######################################################################################################

steps:
# Clone the repository.
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--single-branch', '--branch',
         'main', 'https://github.com/sarath2812/gcp_vertexai',
         '--depth', '1',
         '--verbose']
  id: 'Clone Repository'
logsBucket: 'gs://aivertex-bucket/custom_model_bucket/'


