# /**
#  * @author Sarath Chandra Asapu
#  * @email sarath.chandra.asapu@accenture.com
#  * @create date 2021-09-17 13:09:02
#  * @modify date 2021-09-17 13:09:02
#  * @desc [description]
#  */

# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:sarath2812/gcp_vertexai
  volumes:
  - name: 'ssh'
    path: /root/.ssh


- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/peak-catbird-324206/myimage:v1', '.']

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'us-central1-docker.pkg.dev/peak-catbird-324206/myimage:v1']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run',  'us-central1-docker.pkg.dev/peak-catbird-324206/myimage:v1']

availableSecrets:
  secretManager:
  - versionName: projects/584418773784/secrets/git-secret-key/versions/1
    env: 'SSH_KEY'
logsBucket: 'gs://aivertex-bucket/cloud_build_logs/' 

# - name: python
# #   entrypoint: pip 
#   args: 
#   -     pip install -r requirements.txt
#   -     python ./pipeline/pipeline_kfp.py
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh

# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 
#            'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/myimage:$SHORT_SHA', '.']


# - name: python
#   entrypoint: pip 
#   args: ["install","-r","requirements.txt"]

# - name: python
#   entrypoint: python
#   args: ["./pipeline/pipeline_kfp.py"]
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh

# - name: python
#   entrypoint: python
#   args: ["./pipeline/pipeline_kfp.py"]
#   volumes:
#   - name: 'ssh'
#     path: /root/.ssh

# - name: 'python'
#     args: 
#     - -C
#     - |
#        cp . ./
#        python ./pipeline/pipeline_kfp.py
#    volumes:
#   - name: 'ssh'
#     path: /root/.ssh

# - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 
#            'us-central1-docker.pkg.dev/peak-catbird-324206/cicdimage:v1', '.']    

